### ISSUE TITLE
Remove remote package from TestNG

### ISSUE THREAD

**Issue by juherr** [testng-team/testng-remote#12]
I was thinking about removing the remote package from TestNG, but how can we manage it?

I think TestNG should not have a dependency to testng-remote but, currently, `TestNG` imports some remote classes (`SuiteDispatcher` and `SuiteSlave`).

Do you have an idea?

**Comment by cbeust** [comment]
Shouldn't TestNG simply depend on `testng-remote`?

**Comment by juherr** [comment]
I don't know if it will work as testng-remote already depends on testng

**Comment by missedone** [comment]
i don't think we can do it now since testng-remote depends on testng which will cause circular dependency.
besides with `SuiteDispatcher` and `SuiteSlave`, there is also `org.testng.xml.ResultContentHandler`  and `org.testng.xml.ResultXMLParser` depends on `*Message`, `IRemoteSuiteListener` and `IRemoteTestListener`
i think we need find a way to abstract them.

**Comment by missedone** [comment]
regards to `SuiteDispatcher` and `SuiteSlave` which enables TestNG to be able running in master/slave mode. After some investigation, i'd suggest to remove the master/slave feature out of TestNG, make it into a sub-module of testng-remote or a small project like testng-remote.
the reason is, i found it's hard to define a set of API for `SuiteDispatcher` and `SuiteSlave` which does not depends on TestNG and TestNG Remote.
to implement master/slave, since it's a separate module, we can make it depend on TestNG and TestNG Remote, and introduce a new main class DistributedTestNG extends TestNG, if people want to use master/slave mode, they need to use this new main class instead.
in this way, we can make the structure for `TestNG` / `TestNG Remote` / `TestNG Distributed` clean and each one has a clear roles of responsibility.
what do you think @cbeust ?

**Comment by missedone** [comment]
BTW, Cedric's weblog http://beust.com/weblog2/archives/000362.html can help understand how master/slave works

**Comment by juherr** [comment]
https://github.com/cbeust/testng/pull/953
